// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: air quality monitorint system ui design

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label2;
void ui_event_Image5(lv_event_t * e);
lv_obj_t * ui_Image5;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label21;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image10;
// CUSTOM VARIABLES
lv_obj_t * uic_Screen1;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label29;
void ui_event_Arc5(lv_event_t * e);
lv_obj_t * ui_Arc5;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Arc6;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Arc7;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label39;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Image14;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_Chart4(lv_event_t * e);
lv_obj_t * ui_Chart4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1295108173[1] = {&ui_img_883963309};
const lv_img_dsc_t * ui_imgset_649865559[1] = {&ui_img_1317788323};
const lv_img_dsc_t * ui_imgset_730713098[1] = {&ui_img_281563486};
const lv_img_dsc_t * ui_imgset_1239583046[1] = {&ui_img_1717175438};
const lv_img_dsc_t * ui_imgset_684782686[1] = {&ui_img_471599554};
const lv_img_dsc_t * ui_imgset_1675718514[1] = {&ui_img_953603658};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_TOP, 2000, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Arc5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_TOP, 2000, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Chart4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_TOP, 2000, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
