// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: air quality monitorint system ui design

#ifndef _AIR_QUALITY_MONITORINT_SYSTEM_UI_DESIGN_UI_H
#define _AIR_QUALITY_MONITORINT_SYSTEM_UI_DESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label2;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label21;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label29;
void ui_event_Arc5(lv_event_t * e);
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Arc6;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Arc7;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label39;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Image14;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Chart4(lv_event_t * e);
extern lv_obj_t * ui_Chart4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_883963309);    // assets/dust-1.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_281563486);    // assets/humidity-1.png
LV_IMG_DECLARE(ui_img_471599554);    // assets/smoke-1.png
LV_IMG_DECLARE(ui_img_co_png);    // assets/co.png
LV_IMG_DECLARE(ui_img_1317788323);    // assets/Fire-1.png
LV_IMG_DECLARE(ui_img_1717175438);    // assets/lpg-1.png
LV_IMG_DECLARE(ui_img_bar_png);    // assets/bar.png
LV_IMG_DECLARE(ui_img_953603658);    // assets/wifi-1.png

// FONTS
LV_FONT_DECLARE(ui_font_temp);
LV_FONT_DECLARE(ui_font_value);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
