// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: air quality monitorint system ui design

#include "ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

// IMAGE DATA: assets/lpg-1.png
const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_1717175438_data[] = {
   
};
const lv_img_dsc_t ui_img_1717175438 = {
    .header.always_zero = 0,
    .header.w = 30,
    .header.h = 50,
    .data_size = sizeof(ui_img_1717175438_data),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = ui_img_1717175438_data
};

