// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: air quality monitorint system ui design

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart4 = lv_chart_create(ui_Screen3);
    lv_obj_set_width(ui_Chart4, 168);
    lv_obj_set_height(ui_Chart4, 238);
    lv_obj_set_x(ui_Chart4, 1);
    lv_obj_set_y(ui_Chart4, -2);
    lv_obj_set_align(ui_Chart4, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart4, LV_CHART_TYPE_SCATTER);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart4_series_1 = lv_chart_add_series(ui_Chart4, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart4_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart4, ui_Chart4_series_1, ui_Chart4_series_1_array);



    lv_obj_add_event_cb(ui_Chart4, ui_event_Chart4, LV_EVENT_ALL, NULL);

}
